[2024-11-02T19:52:27.480+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-02T19:52:27.496+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transform_data.success manual__2024-11-02T19:52:21.921935+00:00 [queued]>
[2024-11-02T19:52:27.505+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transform_data.success manual__2024-11-02T19:52:21.921935+00:00 [queued]>
[2024-11-02T19:52:27.505+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-11-02T19:52:27.518+0000] {taskinstance.py:2888} INFO - Executing <Task(_BashDecoratedOperator): success> on 2024-11-02 19:52:21.921935+00:00
[2024-11-02T19:52:27.524+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=119) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-02T19:52:27.526+0000] {standard_task_runner.py:72} INFO - Started process 129 to run task
[2024-11-02T19:52:27.527+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'transform_data', 'success', 'manual__2024-11-02T19:52:21.921935+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/transform_data.py', '--cfg-path', '/tmp/tmpabikhn4r']
[2024-11-02T19:52:27.529+0000] {standard_task_runner.py:105} INFO - Job 39: Subtask success
[2024-11-02T19:52:27.572+0000] {task_command.py:467} INFO - Running <TaskInstance: transform_data.success manual__2024-11-02T19:52:21.921935+00:00 [running]> on host 1866d1dd18ef
[2024-11-02T19:52:27.652+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='transform_data' AIRFLOW_CTX_TASK_ID='success' AIRFLOW_CTX_EXECUTION_DATE='2024-11-02T19:52:21.921935+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-02T19:52:21.921935+00:00'
[2024-11-02T19:52:27.653+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-02T19:52:27.675+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-02T19:52:27.675+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "The DAG is running well"']
[2024-11-02T19:52:27.686+0000] {subprocess.py:86} INFO - Output:
[2024-11-02T19:52:27.688+0000] {subprocess.py:93} INFO - The DAG is running well
[2024-11-02T19:52:27.688+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-11-02T19:52:27.714+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-02T19:52:27.714+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=transform_data, task_id=success, run_id=manual__2024-11-02T19:52:21.921935+00:00, execution_date=20241102T195221, start_date=20241102T195227, end_date=20241102T195227
[2024-11-02T19:52:27.749+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-02T19:52:27.766+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-02T19:52:27.767+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
